# rustfmt configuration for gguf_rs
# See https://rust-lang.github.io/rustfmt/ for full configuration options

# Stable features
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Code formatting
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 80
struct_variant_width = 80
array_width = 80
chain_width = 80
single_line_if_else_max_width = 80

# Imports
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# Function definitions
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Comments and documentation
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Misc formatting
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true
condense_wildcard_suffixes = true
format_macro_matchers = true
format_macro_bodies = true

# String formatting
format_strings = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Where clause formatting
where_single_line = false
force_multiline_blocks = false

# Match formatting
match_block_trailing_comma = false
match_arm_blocks = true
match_arm_leading_zero = true

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Unstable features (require nightly)
# Uncomment these if using nightly Rust
# unstable_features = true
# format_generated_files = true
# skip_children = false