//! Create and read back a small, unquantized GGUF v3 file.
//!
//! By default this writes `target/examples/test-model.gguf`. Pass a path after
//! `--` to choose another destination.

#[cfg(feature = "std")]
use gguf_rs_lib::{
    builder::GGUFBuilder, format::MetadataValue, reader::GGUFFileReader, GGUFError, Result,
};
#[cfg(feature = "std")]
use std::{fs::File, path::PathBuf};

#[cfg(feature = "std")]
fn main() -> Result<()> {
    let output = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("target/examples/test-model.gguf"));

    if let Some(parent) = output.parent().filter(|path| !path.as_os_str().is_empty()) {
        std::fs::create_dir_all(parent)?;
    }

    let result = GGUFBuilder::simple("test-model", "Generated by create_test_gguf")
        .add_metadata("example.version", MetadataValue::U32(1))
        .add_f32_tensor("weights", vec![2, 2], vec![1.0, 2.0, 3.0, 4.0])?
        .build_to_file(&output)?;

    let reader = GGUFFileReader::new(File::open(&output)?)?;
    if reader.tensor_count() != 1 {
        return Err(GGUFError::Format(format!(
            "read-back expected 1 tensor, found {}",
            reader.tensor_count()
        )));
    }

    println!("wrote {} bytes to {}", result.total_bytes_written, output.display());
    println!(
        "read back {} metadata entries and {} tensor descriptor",
        reader.metadata().len(),
        reader.tensor_count()
    );

    Ok(())
}

#[cfg(not(feature = "std"))]
fn main() {
    eprintln!("create_test_gguf requires the default `std` feature");
    std::process::exit(1);
}
